# encoding: utf-8
development:
  adapter: mysql2
  encoding: utf8
  database: test_app_development
  pool: 5
  username: root
  password: 'holloworld91@'
test:
  adapter: mysql2
  encoding: utf8
  database: test_app_test
  pool: 5
  username: root
  password: 'holloworld91@'
production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: test_app_pr
  pool: 5
  username: root
  password: "holloworld91@"
