development:
  adapter: mysql2
  encoding: utf8
  database: test_app_development
  pool: 5
  username: root
  password: zaqxsw

test:
  adapter: mysql2
  encoding: utf8
  database: test_app_test
  pool: 5
  username: root
  password: zaqxsw